### ISSUE TITLE
テストケース分析(気づいたこと)

### ISSUE THREAD

**Issue by pysan3** [siro53/grpwk#4]
all notes and notices about the test cases here

**Comment by pysan3** [comment]
**len(s_i)の集計**  (100は20より長いもの
![image](https://user-images.githubusercontent.com/41065736/69885690-b92ffd80-1321-11ea-8b77-07985fe70ed8.png)
あまり偏りはなさそう

**Comment by pysan3** [comment]
**sum(len(s_i)) == len(t)**
![image](https://user-images.githubusercontent.com/41065736/69885851-a79b2580-1322-11ea-9b06-56a10e3ffba0.png)

**Comment by pysan3** [comment]
それぞれのテストケースのlen(s_i)の最大値
[0, 1, 2, 3, 4]
![image](https://user-images.githubusercontent.com/41065736/69885883-d2857980-1322-11ea-9f80-7848ffcef4ca.png)

**Comment by pysan3** [comment]
**dat0におけるlen(s_i)==nの個数**
対応関係が見づらいが、半分により下が個数
![image](https://user-images.githubusercontent.com/41065736/69885984-3a3bc480-1323-11ea-8d56-dcef6bb809d7.png)
- 特に短いときはcount(n) > count(n+1)を必ず満たしてる
  - 何かしらのnに関する1次式では？(傾きが負)

**Comment by pysan3** [comment]
**虫食いデータのxの個数**
![image](https://user-images.githubusercontent.com/41065736/69886083-a1f20f80-1323-11ea-9fe0-d4d9c98702ed.png)
- ちょうど2/5

**Comment by pysan3** [comment]
**xが連続する個数の頻出度**
![image](https://user-images.githubusercontent.com/41065736/69886128-d5cd3500-1323-11ea-8e1b-ed17e39f3f3b.png)
- y=(2/5)^nより多分虫は一様乱数に従って食い散らかす

**Comment by udemegane** [comment]
**爆速手抜きプログラム検証結果**
 環境:
  hp spectre x360 13 ae-0xx
  Windows 10 pro ver1903
  CPU i7-8550u 1.80Ghz　(TB時3.3GHz前後)
  RAM　16GB

-------------------------------------------------------

入力のxをaにすべて置換
 実行時間:
  ave 0.070.5sec

 編集距離:
  case0:94613
  case1:94309
  case2:94714
  case3:94295
  case4:94415

-------------------------------------------------------

入力をそのまま出力
 実行時間:
  ave 0.001sec (clock関数使って計測したが多分早すぎて正確に測定できてない　
gettimeofdayとか使えば正確に測れそうだけどやる意味を感じなかったのでしませんでした)

 編集距離:
  case0:160049
  case1:159864
  case2:159684
  case3:159699
  case4:159728

-------------------------------------------------------



＊ブルートフォースまだ組んでないので何とも言えないが去年と似た問題ならｘをaに置換するだけのプログラムの95000という数字はかなりよさげに見える。

＊編集距離の計算に結構時間かかるので今後の取り組み方次第では改善の必要有？

**Comment by siro53** [comment]
編集距離を計算するの、[これ](http://handasse.blogspot.com/2009/04/c_29.html)を参考に実装してみようかな
今回文字数が少ないので編集距離の計算が早くなりそうかもしれない

**Comment by udemegane** [comment]
おお、それはとてもありがたい
薄型ラップトップで実行したってのもあるけど（激しく後悔）１０ケース調べるだけでそれなりの時間かかったから高速編集距離プログラムは割と恩恵はある気がする

**Comment by pysan3** [comment]
正直今回は文字列が無限に長いと仮定してしまって、横ずれ(1つ追加や1つ消去)は発生しないとしてしまっていいんじゃないかな
つまり1文字ずつ比較して違ったら編集距離+1

**Comment by udemegane** [comment]
なるほど
一回Cで普通のDPで組んだんだけどメモリ確保は特に問題にならなかったから（mallocで(4*10^5)^2確保できた）確かにその考えはいいかもしれない

**Comment by siro53** [comment]
その方が良さそうだね

**Comment by pysan3** [comment]
O(N)♪

**Comment by udemegane** [comment]
そういえば昨日思いついたアルゴリズムについて触れるのを忘れていたので概要だけisuueの別スレッドに飛ばします

**Comment by SayakaYakumo** [comment]
**各アルファベットのxになっている数、それらの割合**
![image](https://user-images.githubusercontent.com/53550334/69915889-7e4fd600-1497-11ea-9657-d7670fa0d8a3.png)

- a, b, d, cの順に多い

- xになりやすさは同じ

**Comment by YIKA339** [comment]
少し前の話題になるんだけど、sum(len(s_i))==len(t)なのに、S_iを並べただけじゃ一致しないの個人的に腑に落ちてない・・・
スライドの定義が間違ってる？それともS_i同士で重複がある？(または私の認識がそもそも間違ってる？)
なんか場違いなこと言ってたらごめんなさい。

**Comment by pysan3** [comment]
> スライドの定義が間違ってる？それともS_i同士で重複がある？(または私の認識がそもそも間違ってる？)

いや、スライドの定義は写真のとおりだから、多分スライドの例が間違ってるんじゃない？
![image](https://user-images.githubusercontent.com/41065736/69940107-c701a080-1524-11ea-9809-0182d361a181.png)
s_iをうまいこと組み合わせたら重複もあまりもなくtと一致するっていうことだと思う

**Comment by pysan3** [comment]
一応、今s全体に含まれる[a,b,c,d]のそれぞれの個数とtの中のそれぞれの個数を比較したけど、同数でした
s_iに重複があるなら一致しないだろうから多分ないと思っていいんじゃないかな...

**Comment by YIKA339** [comment]
あーそうか、Sの定義の0<i<kって別に1から順に並んでるって訳じゃないのか...
検証までしてくれてありがとうm(_ _  )m

**Comment by SayakaYakumo** [comment]
**2文字のアルファベットの組の出現数とその確率**
![image](https://user-images.githubusercontent.com/53550334/69960162-245d1800-154c-11ea-8e61-616a455dbf6e.png)

- **dcの組は存在しない**

- a -> a:40%, b:20%, c:20%, d:20%

- b -> a:40%, b:20%, c:10%, d:30%

- c -> a:30%, b:30%, c:10%, d:30%

- d -> a:50%, b:40%, c:00%, d:10%

**Comment by udemegane** [comment]
話によると友人がs_iを使わずに各種規則性のみで精度80%に乗せたらしいです
xをaに置換するよりも効率の良い圧縮方法があったらほぼノーコストで精度を上げられるのでぜひとも知りたいけどどうすればいいのだろう
